server:
  port: 8080
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 180200
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-security
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration